# Site settings
title: PALNET S.A
email: palnetsa@gmail.com
description: "baseurl: Palnet S.A Juan Jose Vaglica. Juan José Vaglica Experiencia, cumplimiento y flexibilidad. Construcción de obras edilicias, ingeneria, industria y logisitica,estaciones de servicio. Montevideo -Uruguay"

#baseurl: "/palnet/" # the subpath of your site, e.g. /blog
#url: "http://palnetsa.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:categories/:title
